RodriguesLembra/Models/Realm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RodriguesLembra.Models
{
    public class Realm
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid RealmID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }

        /* Navigation Properties */
        [ForeignKey("UserID")]
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<Todo> Todos { get; set; }
    }
}

RodriguesLembra/ViewModels/RealmViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RodriguesLembra.ViewModels
{
    public class CreateRealmViewModel
    {
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Nome é obrigatório")]
        public string Name { get; set; }

        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Descrição é obrigatório")]
        public string Description { get; set; }
    }
}

RodriguesLembra/Controllers/PartialsController.cs
using RodriguesLembra.DAL;
using RodriguesLembra.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RodriguesLembra.Controllers
{
    public class PartialsController : Controller
    {
        public PartialViewResult Realms()
        {
            List<Realm> realms = new List<Realm>();
            if (User.Identity.IsAuthenticated)
            {
                using (var context = new ApplicationDbContext())
                {
                    realms = context.Realms.Where(m => m.User.UserName.Equals(User.Identity.Name))
                        .Include(m => m.Todos)
                        .OrderBy(m => m.Name)
                        .ToList();
                }
            }

            return PartialView("_Realms", realms);
        }

        public PartialViewResult Score()
        {
            using (var context = new ApplicationDbContext())
            {
                var score = "0";
                if (User.Identity.IsAuthenticated)
                {
                    score = context.Users.First(m => m.UserName.Equals(User.Identity.Name))
                        .Score.ToString();
                }

                return PartialView("_Score", score);
            }
        }

        public PartialViewResult RealmsDropDown()
        {
            List<Realm> realms = new List<Realm>();
            if (User.Identity.IsAuthenticated)
            {
                using (var context = new ApplicationDbContext())
                {
                    realms = context.Realms.Where(m => m.User.UserName.Equals(User.Identity.Name))
                        .Include(m => m.Todos)
                        .OrderBy(m => m.Name)
                        .ToList();
                }
            }

            return PartialView("_RealmsDropDown", realms);
        }

        public PartialViewResult AccountInfo()
        {
            string name = string.Empty;
            if (User.Identity.IsAuthenticated)
            {
                using (var context = new ApplicationDbContext())
                {
                    name = context.Users.First(m => m.UserName.Equals(User.Identity.Name)).Name;
                }
            }

            return PartialView("_AccountInfo", name);
        }
    }
}

RodriguesLembra/Controllers/RealmsController.cs
using RodriguesLembra.DAL;
using RodriguesLembra.Models;
using RodriguesLembra.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RodriguesLembra.Controllers
{
    [Authorize]
    public class RealmsController : Controller
    {
        // GET: Realms
        public ActionResult Index()
        {
            var list = new List<Realm>();
            using (var context = new ApplicationDbContext())
            {
                var userId = context.Users.First(m => m.UserName.Equals(User.Identity.Name)).Id;

                list = context.Realms.Where(m => m.UserID.Equals(userId))
                    .OrderBy(m => m.Name)
                    .Include(m => m.Todos)
                    .ToList();
            }

            return View(list);
        }

        // GET: Realms/Details
        public ActionResult Details(Guid id, bool error = false, bool success = false)
        {
            using (var context = new ApplicationDbContext())
            {
                var userId = context.Users.First(m => m.UserName.Equals(User.Identity.Name)).Id;
                var realm = context.Realms
                    .Include(m => m.Todos)
                    .First(m => m.RealmID.Equals(id));

                if (error)
                    ViewBag.ErrorMessage = "Eita, deu ruim! Liga pra mim que a gente resolve ;)";

                if (success)
                    ViewBag.Message = "Tudo certinho, moça! Mas não esquece de mim :3";

                if (realm.UserID == userId)
                {
                    return View(realm);
                }
                else
                {
                    return View("Index", "Home");
                }
            }
        }

        // GET: Realms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Realms/Create
        [HttpPost]
        public ActionResult Create(CreateRealmViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string userId = string.Empty;
                    using (var context = new ApplicationDbContext())
                    {
                        userId = context.Users.First(m => m.UserName.Equals(User.Identity.Name)).Id;

                        Realm realm = new Realm
                        {
                            Name = model.Name,
                            Description = model.Description,
                            UserID = userId
                        };

                        context.Realms.Add(realm);
                        var response = context.SaveChanges();

                        if (response > 0)
                            return RedirectToAction("Index");
                    }
                }

                ViewBag.ErrorMessage = "Eita, deu ruim! Liga pra mim que a gente resolve ;)";
                return View(model);
            }
            catch
            {
                ViewBag.ErrorMessage = "Eita, deu ruim! Liga pra mim que a gente resolve ;)";
                return View(model);
            }
        }

        // GET: Realms/Delete/5
        public ActionResult Delete(Guid id)
        {
            using (var context = new ApplicationDbContext())
            {
                var userId = context.Users.First(m => m.Email.Equals(User.Identity.Name)).Id;
                var realm = context.Realms.Find(id);

                if (realm == null)
                    return RedirectToAction("Index");

                if (realm.UserID != userId)
                    return RedirectToAction("Index");

                return View(realm);
            }
        }

        // POST: Realms/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            using (var context = new ApplicationDbContext())
            {
                Realm realm = context.Realms.Find(id);
                try
                {
                    if (ModelState.IsValid)
                    {
                        context.Realms.Remove(realm);
                        var response = context.SaveChanges();

                        if (response > 0)
                            return RedirectToAction("Index");
                    }

                    ViewBag.ErrorMessage = "Eita, deu ruim! Liga pra mim que a gente resolve ;)";
                    return View(realm);
                }
                catch
                {
                    ViewBag.ErrorMessage = "Eita, deu ruim! Liga pra mim que a gente resolve ;)";
                    return View(realm);
                }
            }
        }
    }
}

RodriguesLembra/Views/Shared/_AccountInfo.cshtml
@using Microsoft.AspNet.Identity
@model string

@if (Request.IsAuthenticated)
{
    <li>
        <a href="#"><strong>@(Model)</strong></a>
    </li>

    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
    {
        @Html.AntiForgeryToken()
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    }
}
else
{
    <li>@Html.ActionLink("Register", "Registrar", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
    <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
}

RodriguesLembra/Views/Shared/_Layout.cshtml
@using System.Security.Claims

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mateus Rodrigues">

    <meta name="application-name" content="Rodrigues Lembra!" />
    <meta name="msapplication-TileColor" content="#5ab75b" />
    <meta name="msapplication-square70x70logo" content="~/Content/Images/tiny.png" />
    <meta name="msapplication-square150x150logo" content="~/Content/Images/square.png" />
    <meta name="msapplication-wide310x150logo" content="~/Content/Images/wide.png" />
    <meta name="msapplication-square310x310logo" content="~/Content/Images/large.png"/>

    <title>Rodrigues Lembra! - @ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- MetisMenu CSS -->
    <link href="~/Content/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Timeline CSS -->
    <link href="~/Content/timeline.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--
    To collect end-user usage analytics about your application,
    insert the following script into each page you want to track.
    Place this code immediately before the closing </head> tag,
    and before any other scripts. Your first data will appear
    automatically in just a few seconds.
    -->
    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"e7ec8b82-6f2e-4fcf-bc6a-674f79085952"
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Rodrigues Lembra! ♥</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="glyphicon glyphicon-tasks"></i>  <i class="caret"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        @Html.Action("RealmsDropDown", "Partials")
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="glyphicon glyphicon-user"></i>  <i class="caret"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        @Html.Action("AccountInfo", "Partials")
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
                <li>
                    <p>Score: <strong>@Html.Action("Score", "Partials")</strong> beijo(s)</p>
                </li>
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="@Url.Action("Index", "Home")"><i class="glyphicon glyphicon-dashboard"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Realms")"><i class="glyphicon glyphicon-console"></i> Contextos</a>
                        </li>
                        @Html.Action("Realms", "Partials")
                        <li>
                            <a href="@Url.Action("About", "Home")"><i class="glyphicon glyphicon-question-sign"></i> Sobre</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <hr />
            <footer class="text-center" style="margin-bottom: 10px">
                Feito com <span class="glyphicon glyphicon-heart" style="color: red"></span> para <strong>Leilane</strong>
            </footer>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Scripts/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Scripts/sb-admin-2.js"></script>
</body>
</html>

RodriguesLembra/Views/Shared/_Realms.cshtml
@model IEnumerable<RodriguesLembra.Models.Realm>

<li>
    <a href="#"><span class="glyphicon glyphicon-tasks"></span> Tarefas<span class="fa arrow"></span></a>
    <ul class="nav nav-second-level">
    @foreach (var realm in Model)
    {
        <li>
            <a href="@Url.Action("Details", "Realms", new { id = realm.RealmID })">
                <i class="glyphicon glyphicon-arrow-right"></i> @realm.Name
            </a>
        </li>
    }
    </ul>
    <!-- /.nav-second-level -->
</li>

RodriguesLembra/Views/Shared/_RealmsDropDown.cshtml
@model IEnumerable<RodriguesLembra.Models.Realm>

@foreach (var item in Model)
{
   
    var percentage =
        double.Parse(item.Todos.Count(m => m.IsDone).ToString()) / double.Parse(item.Todos.Count().ToString());
    percentage = percentage * 100;
    var percentageString = percentage.ToString("0.0");
    var percentageStringForComponent = percentage.ToString("0");

    <li>
        <a href="@Url.Action("Details", "Realms", new { id = item.RealmID })">
            <div>
                <p>
                    <strong>@item.Name</strong>
                    <span class="pull-right text-muted">@(percentageString)% Completo</span>
                </p>
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="@(percentageStringForComponent)" aria-valuemin="0" aria-valuemax="100" style="width: @(percentageStringForComponent)%">
                        <span class="sr-only">@(percentageString)% Completo</span>
                    </div>
                </div>
            </div>
        </a>
    </li>
}

RodriguesLembra/Views/Shared/_Score.cshtml
@model String

@Model