RodriguesLembra/Controllers/HomeController.cs
using RodriguesLembra.DAL;
using RodriguesLembra.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RodriguesLembra.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<Todo> tasks = new List<Todo>();
            using (var context = new ApplicationDbContext())
            {
                var userId = context.Users.First(m => m.UserName.Equals(User.Identity.Name)).Id;

                tasks = context.Todos.Where(m => m.Realm.UserID.Equals(userId))
                    .Include(m => m.Realm)
                    .OrderBy(m => m.DueDate)
                    .ThenBy(m => m.Title)
                    .Take(20)
                    .ToList();
            }

            return View(tasks);
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

RodriguesLembra/Controllers/TodosController.cs
using RodriguesLembra.DAL;
using RodriguesLembra.Models;
using RodriguesLembra.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RodriguesLembra.Controllers
{
    [Authorize]
    public class TodosController : Controller
    {
        // GET: Todos/Create
        public ActionResult Create(Guid realmId)
        {
            CreateTodoViewModel model = new CreateTodoViewModel()
            {
                RealmID = realmId,
                DueDate = DateTime.UtcNow.AddHours(-3)
            };

            return View(model);
        }

        // POST: Todos/Create
        [HttpPost]
        public ActionResult Create(CreateTodoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var context = new ApplicationDbContext())
                    {
                        Todo todo = new Todo
                        {
                            Title = model.Title,
                            Description = model.Description,
                            DueDate = model.DueDate,
                            IsDone = false,
                            RealmID = model.RealmID
                        };

                        context.Todos.Add(todo);
                        var response = context.SaveChanges();

                        if (response > 0)
                            return RedirectToAction("Details", "Realms", new { id = model.RealmID, success = true });
                    }
                }

                ViewBag.ErrorMessage = "Erro na criação do contexto de tarefas";
                return View(model);
            }
            catch
            {
                ViewBag.ErrorMessage = "Erro na criação do contexto de tarefas";
                return View(model);
            }
        }

        // GET: Todos/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Todos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Todos/Delete/5
        public ActionResult Delete(Guid id)
        {
            using (var context = new ApplicationDbContext())
            {
                var userId = context.Users.First(m => m.UserName.Equals(User.Identity.Name)).Id;

                var todo = context.Todos.Find(id);

                if (todo == null)
                    return RedirectToAction("Index", "Home");

                if (todo.Realm.UserID != userId)
                    return RedirectToAction("Index", "Home");

                context.Todos.Remove(todo);
                var response = context.SaveChanges();

                if (response > 0)
                    return RedirectToAction("Details", "Realms", new { id = todo.RealmID, success = true });
                else
                    return RedirectToAction("Details", "Realms", new { id = todo.RealmID, error = true });
            }
        }

        public ActionResult ToggleStatus(Guid id, bool fromHomePage = false)
        {
            using (var context = new ApplicationDbContext())
            {
                var todo = context.Todos.Find(id);
                var user = context.Users.First(m => m.UserName.Equals(User.Identity.Name));

                if (todo == null)
                    return RedirectToAction("Index", "Home");
                if (user == null)
                    return RedirectToAction("Index", "Home");

                todo.IsDone = !todo.IsDone;

                if (todo.IsDone)
                    user.Score += 10;
                else
                    user.Score -= 10;

                context.Entry(user).State = System.Data.Entity.EntityState.Modified;
                context.Entry(user).State = System.Data.Entity.EntityState.Modified;
                var response = context.SaveChanges();

                if (fromHomePage)
                    return RedirectToAction("Index", "Home");

                if (response > 0)
                    return RedirectToAction("Details", "Realms", new { id = todo.RealmID, success = true });
                else
                    return RedirectToAction("Details", "Realms", new { id = todo.RealmID, error = true });
            }
        }
    }
}

RodriguesLembra/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Sobre</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-md-12 text-center">
        <p>Rodrigues Lembra! é um software de gerenciamento de tarefas.</p>
        <p>Também, é um presente para a pessoa mais especial do mundo!</p>
        <p>Feliz 2 anos de namoro! <span class="glyphicon glyphicon-heart"></span></p>
    </div>
    <div class="col-md-4 col-md-offset-4">
        <hr />
    </div>
    <div class="col-md-12 text-center">
        <i>
            <p>Te dou esse presente</p>
            <p>Para você perceber</p>
            <p>Que todas as suas tarefas</p>
            <p>Aqui você deve depositar</p>
            <p>Para que assim, você possa</p>
            <p>Apenas de mim lembrar</p>
            <p>E, dessa mesma maneira,</p>
            <p>Eu apenas de você.</p>
        </i>
    </div>
    <br /><br />
    <div class="col-md-12 text-center">
        <p class="blockquote-reverse">14/02/2016<br /><strong>Mateus Rodrigues</strong></p>
    </div>
</div>

RodriguesLembra/Views/Home/Index.cshtml
@model IEnumerable<RodriguesLembra.Models.Todo>
@{
    ViewBag.Title = "Dashboard";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <span class="fa fa-tasks fa-5x"></span>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.Count()</div>
                        <div>Tarefas</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <span class="fa fa-tasks fa-5x"></span>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.Count(p => p.IsDone)</div>
                        <div>Tarefas Completas</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <span class="fa fa-tasks fa-5x"></span>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.Count(p => !p.IsDone)</div>
                        <div>Tarefas para realizar</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <span class="fa fa-tasks fa-5x"></span>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.Count(p => DateTime.UtcNow.AddHours(-3).Date > p.DueDate.Date && !p.IsDone)</div>
                        <div>Tarefas atrasadas</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-clock-o fa-fw"></i> Timeline
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <ul class="timeline">
            @{
                int counter = 0;
            }
            @foreach (var item in Model)
            {
                if (counter % 2 == 0)
                {
                    <li>
                        @if (item.IsDone)
                        {
                            <div class="timeline-badge success"><i class="fa fa-check"></i></div>
                        }
                        else
                        {
                            if (item.DueDate.Date < DateTime.UtcNow.AddHours(-3).Date)
                            {
                                <div class="timeline-badge danger">
                                    <a class="timeline-link" href="@Url.Action("ToggleStatus", "Todos", new { id = item.TodoID, fromHomePage = true })"><i class="fa fa-tasks"></i></a>
                                </div>
                            }
                            else if (item.DueDate.Date == DateTime.UtcNow.AddHours(-3).Date)
                            {
                                <div class="timeline-badge info">
                                    <a class="timeline-link" href="@Url.Action("ToggleStatus", "Todos", new { id = item.TodoID, fromHomePage = true })"><i class="fa fa-tasks"></i></a>
                                </div>
                            }
                            else
                            {
                                <div class="timeline-badge warning">
                                    <a class="timeline-link" href="@Url.Action("ToggleStatus", "Todos", new { id = item.TodoID, fromHomePage = true })"><i class="fa fa-tasks"></i></a>
                                </div>
                            }
                        }

                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">@item.Title</h4>
                                <p>
                                    <small class="text-muted"><i class="fa fa-clock-o"></i> @item.DueDate.ToLongDateString()</small>
                                    <br />
                                    <small class="text-muted"><i class="glyphicon glyphicon-console"></i> @item.Realm.Name</small>
                                </p>
                            </div>
                            <div class="timeline-body">
                                <p>@item.Description</p>
                            </div>
                        </div>
                    </li>
                }
                else
                {
                    <li class="timeline-inverted">
                        @if (item.IsDone)
                        {
                            <div class="timeline-badge success"><i class="fa fa-check"></i></div>
                        }
                        else
                        {
                            if (item.DueDate.Date < DateTime.UtcNow.AddHours(-3).Date)
                            {
                                <div class="timeline-badge danger">
                                    <a class="timeline-link" href="@Url.Action("ToggleStatus", "Todos", new { id = item.TodoID, fromHomePage = true })"><i class="fa fa-tasks"></i></a>
                                </div>
                            }
                            else if (item.DueDate.Date == DateTime.UtcNow.AddHours(-3).Date)
                            {
                                <div class="timeline-badge info">
                                    <a class="timeline-link" href="@Url.Action("ToggleStatus", "Todos", new { id = item.TodoID, fromHomePage = true })"><i class="fa fa-tasks"></i></a>
                                </div>
                            }
                            else
                            {
                                <div class="timeline-badge warning">
                                    <a class="timeline-link" href="@Url.Action("ToggleStatus", "Todos", new { id = item.TodoID, fromHomePage = true })"><i class="fa fa-tasks"></i></a>
                                </div>
                            }
                        }
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">@item.Title</h4>
                                <p>
                                    <small class="text-muted"><i class="fa fa-clock-o"></i> @item.DueDate.ToLongDateString()</small>
                                    <br />
                                    <small class="text-muted"><i class="glyphicon glyphicon-console"></i> @item.Realm.Name</small>
                                </p>
                            </div>
                            <div class="timeline-body">
                                <p>@item.Description</p>
                            </div>
                        </div>
                    </li>
                }
                counter++;
            }
        </ul>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->